---
title: "Game of Thrones Deadpool"
output: github_document
---

#### Rules:
* 1 point given to each player for correctly determining each character's end. 
* An extra point will be rewarded for correctly guessing if they are turned to a White Walker.

#### Prizes: 

* 1st: `$15`
* 2nd: `$10`
* 3rd: `$5`


#### Current Standings:

```{r echo=FALSE, message=F, warning=F}
library(tidyverse)
library(knitr)

read_csv("Data.csv") %>% 
  gather(Player, Guess, -c(1:7)) %>% 
  gather(Episode, Actual, -Character, -Guess, -Player) %>% 
  mutate(Score = ifelse(Actual == Guess, 1, 0),
         # assessing if it's a white walker guess, then it's worth 2
         Score = ifelse(Actual == "White Walker" & Guess == "White Walker", 2, Score)) %>% 
  group_by(Episode, Player) %>% 
  summarise(Score = sum(Score, na.rm = T)) %>% 
  arrange(desc(Score)) %>% 
  spread(Episode, Score) %>% 
  kable
```

#### Guesses:

```{r echo=FALSE, message=F, warning=F}
read_csv("Data.csv") %>% 
  select(-contains("Episode")) %>% 
  kable
```

Last generated: ```r Sys.Date()```
